name: mini_web_sample
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: Mike Mitterer <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  build: ^0.12.0

  html: ^0.13.0
  git_version:
    path: ../..

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

dev_dependencies:

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
